baseURL = 'https://timfo.xyz/'
locale = 'en-us'
title = "Tim's Portolio"
theme = ["github.com/luizdepra/hugo-coder"]
defaultcontentlanguage = "en"

[params]
  author = "Timothy R."
  info =  """Featuring my personal projects, experience & learning."""
  keywords = "blog,personal"
  colorScheme = "dark"

  [[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"


  [[menu.main]]
  name = "About"
  weight = 1
  url  = "about/"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/t1mothyr"

[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 2
  url = "mailto:contact@timfo.xyz"

[[params.social]]
  name = "Email"
  icon = "fa-solid fa-rss fa-2x"
  weight = 2
  url = "https://timfo.xyz/index.xml"


[imaging]
  [imaging.exif]
    disableDate = true
    disableLatLong = true
